This bean should be considered only when app is running in kubernetes
spring-cloud/spring-cloud-kubernetes pull request #667
Opened 2020-10-27 11:51 UTC by flareupdigital

When spring boot app runs on bare metal, you get an error: No qualifying bean of type 'io.fabric8.kubernetes.client.Config' available.

2020-11-24 00:54 UTC, ryanjbaxter requested changes
Looks like you are missing a dependency in the module for the conditional...see circleci results.

2020-11-24 00:55 UTC, ryanjbaxter commented
Also would be good if you could submit this to the 1.1.x branch

2021-05-20 22:22 UTC, wind57 commented
@ryanjbaxter I've tried to fix this one [here](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/800/files)

2021-05-25 17:11 UTC, wind57 commented
@ryanjbaxter this one can be closed? the changes were merged by you in a diff PR

2021-05-25 18:07 UTC, closed without merging