toggling k8s configuration with a relevant property fixes gh-585
spring-cloud/spring-cloud-kubernetes pull request #680
Opened 2020-12-02 21:13 UTC by Haybu

2020-12-02 21:41 UTC, ryanjbaxter reviewed
Should we make similar changes here?
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/reload/KubernetesClientConfigReloadAutoConfiguration.java

Checstyle is failing as well

2020-12-03 16:23 UTC, Haybu commented
I considered changing it before but didn't see the original condition on class `@ConditionalOnProperty(value = "spring.cloud.kubernetes.enabled", matchIfMissing = true)` thought there is an implementation change that made the properties obsolete. If all the same, I can apply the same modified condition and tests.

2020-12-03 20:15 UTC, ryanjbaxter commented
Sounds good

On Thu, Dec 3, 2020 at 11:23 AM Haytham Mohamed <notifications@github.com>
wrote:

> I considered changing it before but didn't see the original condition on
> class @ConditionalOnProperty(value = "spring.cloud.kubernetes.enabled",
> matchIfMissing = true) thought there is an implementation change that
> made the properties obsolete. If all the same, I can apply the same
> modified condition and tests.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-kubernetes/pull/680#issuecomment-738116307>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAD77XVXLECZ5PG55UJQQ73SS63QJANCNFSM4ULBTK6Q>
> .
>

2020-12-06 22:02 UTC, ryanjbaxter requested changes

2020-12-06 22:02 UTC, ryanjbaxter commented on spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/src/main/resources/bootstrap-kubernetes.yaml
> +        enabled: true
Isn't this the default?

2020-12-06 22:02 UTC, ryanjbaxter commented on spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/reload/KubernetesClientConfigReloadAutoConfiguration.java
> +@Conditional(ConditionalKubernetesAndConfigEnabled.class)
Shouldn't this be `@ConditionalKubernetesAndConfigEnabled`?

2020-12-07 22:53 UTC, Haybu commented on spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/src/main/resources/bootstrap-kubernetes.yaml
> +        enabled: true
correct. it should be the default.

2020-12-08 00:31 UTC, ryanjbaxter requested changes
Sorry one more thing I just noticed

2020-12-08 00:31 UTC, ryanjbaxter commented on spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/reload/ConfigReloadAutoConfiguration.java
> +@ConditionalOnProperty(value = { "spring.cloud.kubernetes.config.enabled", "spring.cloud.kubernetes.enabled" },
Couldn't we use `@ConditionalOnKubernetesAndConfigEnabled` here too?

2020-12-08 16:17 UTC, merged