Bumping kubernetes client to 11.0.0
spring-cloud/spring-cloud-kubernetes pull request #708
Opened 2020-12-22 07:12 UTC by yue9944882

2020-12-22 20:20 UTC, ryanjbaxter commented
thanks!

2020-12-23 13:54 UTC, ryanjbaxter commented
@yue9944882 let me know when this is ready to review

2020-12-25 07:21 UTC, yue9944882 commented
@ryanjbaxter i think it's ready for review, but the CI job is flaking due to "Connection Reset", can you help re-run the test?

2020-12-26 02:07 UTC, wind57 commented
@yue9944882 this is not going to work either way. you updated to `2.0.1-SNAPSHOT` but for example the image is missing here : https://hub.docker.com/r/springcloud/spring-cloud-kubernetes-configuration-watcher/tags?page=1&ordering=last_updated . We need indeed Ryan's help. I would also appreciate an explanation how this is possible... and how that image is pushed.

2020-12-28 05:25 UTC, yue9944882 commented
> you updated to 2.0.1-SNAPSHOT but for example the image is missing here

i thought the image is pulled from dockerhub before, but actally it is supposed to be built locally from `spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher` by running mvn install. that's why i refactored the script for integration test

2020-12-28 16:56 UTC, wind57 commented
oh! I see you changed `run.sh` indeed... 

you can always push a dummy commit (like a new line somewhere) to re-trigger the build, btw.

2020-12-31 07:59 UTC, yue9944882 commented
@ryanjbaxter @wind57 hooray it passed!

2021-01-19 22:10 UTC, ryanjbaxter commented
@yue9944882 can you fix the merge conflicts?

2021-01-19 22:15 UTC, ryanjbaxter requested changes

2021-01-19 22:15 UTC, ryanjbaxter commented on spring-cloud-kubernetes-integration-tests/run.sh
> +	cd $CURRENT_DIR/../spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher
The build should be run before running this script so this is unnecessary

2021-01-19 22:15 UTC, ryanjbaxter commented on spring-cloud-kubernetes-commons/pom.xml
> +		<dependency>
Why is this added?

2021-02-10 15:59 UTC, merged